{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="maincontentheader">
<h2>{"Edit attribute filter"|i18n("design/standard/syndication/edit")}</h2>
</div>

{"Enter syndication object attribute identifier."|i18n("design/standard/syndication/edit")}<br />
<input type="text" name="AttributeName" value="{$default_attribute|wash}" />
