{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let comment_cols=60
     comment_rows=10
     uri=$wizard.url
}
<form action={$uri|ezurl} method="post" name="Syndication">

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{"Edit Syndication Import - %name ( step %step )"|i18n( "design/standard/syndication/edit",
                                                                "",
                                                                hash( "%name", $syndication_import.name|wash,
                                                                      "%step", $wizard.current_step|sum(1) ) )}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

{section show=gt($wizard.error_count, 0)}
    {section loop=$wizard.error_list}
        <div class="error">
            {$:item|wash}
        </div>
    {/section}
{/section}

{section show=gt($wizard.warning_count, 0)}
    {section loop=$wizard.warning_list}
        <div class="warning">
            {$:item|wash}
        </div>
    {/section}
{/section}

<div class="block">

    {include uri=$wizard.step_template wizard=$wizard}

</div>

</div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
        <input type="submit" name="PreviousButton" value="{"&lt;&lt; Previous"|i18n("design/standard/syndication/edit")}" />
        <input type="submit" name="NextButton" value="{"Next &gt;&gt;"|i18n("design/standard/syndication/edit")}" />
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>

</form>

{/let}