{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let uri=concat("syndication/edit_import_filter/", $import_filter.id)}

<form action={$uri|ezurl} method="post" name="Syndication">

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{"Edit Syndication Import Filter - %name"|i18n("design/standard/syndication/edit", "", hash( "%name", $import_filter.import.name|wash ) )}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

<div class="block">

    {include uri=$filter.edit_template}

    <br />


</div>

    </div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
    {include uri="design:gui/button.tpl" id_name="Store" value="Store"|i18n("design/standard/syndication/edit")}
    {include uri="design:gui/button.tpl" id_name="Cancel" value="Cancel"|i18n("design/standard/syndication/edit")}
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>

</form>

{/let}