{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let description_cols=60
     description_rows=10
     uri=concat("syndication/edit/", $syndication_feed.id )}

<form action={$uri|ezurl} method="post" name="Syndication">

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{"Edit Syndication - %name"|i18n("design/standard/syndication/edit", "", hash( "%name", $syndication_feed.name|wash ) )}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="block">
        <label>{"Name"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
        {include uri="design:gui/lineedit.tpl" id_name=Name value=$syndication_feed.name|wash}
    </div>

    <div class="block">
        <label>{"Identifier"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
        {include uri="design:gui/lineedit.tpl" id_name=Identifier value=$syndication_feed.identifier|wash}
    </div>

    <div class="block">
        <label>{"Enabled"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
        <input type="checkbox" name="Active" {section show=$syndication_feed.enabled|eq(1)}checked="checked"{/section}>{"Active"|i18n("design/standard/syndication/edit")}</input>
    </div>

    <div class="block">
        <label>{"Object expiry time"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
        {include uri="design:gui/lineedit.tpl" id_name=ObjectExpiryTime value=$syndication_feed.object_expiry_time|wash}&nbsp;{"days"|i18n("design/standard/syndication/edit")}
    </div>

    <div class="block">
    <label>{"Cache expiry time ( 0 will disable cache )"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
    {include uri="design:gui/lineedit.tpl" id_name=CacheTimeout value=$syndication_feed.cache_timeout|wash}&nbsp;{"minutes"|i18n("design/standard/syndication/edit")}
    </div>

    <div class="block">
    <label>{"Force cronjob cache. This will disable cache creation on SOAP calls. ( Recommended )"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
    <input type="checkbox" name="ForceCronjobCache" {section show=$syndication_feed.force_cronjob_cache|eq(1)}checked="checked"{/section}>{"Cronjob cache"|i18n("design/standard/syndication/edit")}</input>
    </div>

    <div class="block">
    <label>{"Description for subscribers"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
    <textarea name="PublicDescription" class="description" cols="{$description_cols}" rows="{$description_rows}">{$syndication_feed.public_comment|wash}</textarea>
    </div>

    <div class="block">
    <label>{"Feed Sources"|i18n("design/standard/syndication/edit")}:</label><div class="labelbreak"></div>
    <table class="list" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <th>{"Name"|i18n("design/standard/syndication/edit")}</th>
            <th>{"Type"|i18n("design/standard/syndication/edit")}</th>
            <th>{"Location"|i18n("design/standard/syndication/edit")}</th>
            <th class="tight">{"Edit"|i18n("design/standard/syndication/edit")}</th>
            <th class="tight">{"Remove"|i18n("design/standard/syndication/edit")}</th>
        </tr>

        {section name=Source loop=$syndication_feed.draft_source_list sequence=array(bglight,bgdark)}
            <tr>
                <td class="{$Source:sequence}"><a href={$Source:item.node.url_alias|ezurl}>{$Source:item.node.name|wash}</a></td>
                <td class="{$Source:sequence}">{$Source:item.type_string|wash}</td>
                <td class="{$Source:sequence}">{$Source:item.node.path_identification_string|wash}</td>
                <td class="{$Source:sequence}"><div class="listbutton"><a href={concat( "syndication/list_source_filter/",$Source:item.id, '/(generate_drafts)/1' )|ezurl}><img class="button" src={"edit.png"|ezimage} width="16" height="16" alt="Edit" /></a></div></td>
                <td class="{$Source:sequence}" width="1"><input type="checkbox" name="RemoveSourceIDArray[]" value="{$Source:item.id}"></td>
            </tr>
        {/section}

        <tr>
            <td colspan="4">
            {include uri="design:gui/button.tpl" id_name=AddSourceButton value="New Source"|i18n("design/standard/syndication/edit")}
            </td>
            <td align="right">
            <input type="image" name="RemoveSourceButton" value="{'Remove'|i18n('design/standard/syndication/edit')}" src={"trash.png"|ezimage} />
            </td>
        </tr>
    </table>
    </div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
    <input class="button" type="submit" name="Store" value="{'Ok'|i18n( 'ezxnewsletter' )}" title="{'Apply the changes.'|i18n( 'crm' )}" />
    <input class="button" type="submit" name="Cancel" value="{'Cancel'|i18n( 'ezxnewsletter' )}" title="{'Cancel the changes.'|i18n( 'crm' )}" />
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>

</form>

{/let}