{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form action={concat("syndication/edit_source_filter/", $source_filter.id, "/", $source_filter.version)|ezurl} method="post" name="Syndication">
<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{"Edit Syndication Feed Filters - %name"|i18n("design/standard/syndication/edit", "", hash( "%name", $source_filter.feed.name|wash ) )}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="block">
        {include uri=$filter.edit_template}
    </div>

</div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
    {include uri="design:gui/button.tpl" id_name="Store" value="Store"|i18n("design/standard/syndication/edit")}
    {include uri="design:gui/button.tpl" id_name="Cancel" value="Cancel"|i18n("design/standard/syndication/edit")}
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>
</form>