{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let uri=concat("syndication/import_list")}

<form action={$uri|ezurl} method="post" name="Syndication">

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{"Syndication import list"|i18n("design/standard/syndication/list")}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

<div class="block">
<table class="list" width="100%" cellpadding="0" cellspacing="0" border="0">
<tr>
    <th>{"Name"|i18n("design/standard/syndication/list")}</th>
    <th>{"Edit waiting objects"|i18n("design/standard/syndication/list")}</th>
    <th>{"Active"|i18n("design/standard/syndication/list")}</th>
    <th class="tight">{"Installed"|i18n("design/standard/syndication/list")}</th>
    <th class="tight">{"Installing"|i18n("design/standard/syndication/list")}</th>
    <th class="tight">{"Pending"|i18n("design/standard/syndication/list")}</th>
    <th class="tight">{"Failed"|i18n("design/standard/syndication/list")}</th>
    <th class="tight">{"Without status"|i18n("design/standard/syndication/list")}</th>
    <th class="tight">{"Edit"|i18n("design/standard/syndication/list")}</th>
    <th class="tight">{"Remove"|i18n("design/standard/syndication/list")}</th>
</tr>

{section name=Syndication loop=$import_list sequence=array(bglight,bgdark)}
<tr class="{$Syndication:sequence}">
    <td><a href={concat("syndication/pending_edit/",$Syndication:item.id)|ezurl}>{$Syndication:item.name|wash}</a></td>
    <td><a href={concat("syndication/pending_edit/",$Syndication:item.id)|ezurl}><img class="button" src={"edit.png"|ezimage} width="16" height="16" alt="Edit" /></a></div></td>
    <td>{cond( $Syndication:item.enabled, 'yes'|i18n('design/standard/syndication/list'), 'no'|i18n('design/standard/syndication/list'))}</td>
    <td>{$Syndication:item.installed_count|wash}</td>
    <td>{$Syndication:item.installing_count|wash}</td>
    <td>{$Syndication:item.pending_count|wash}</td>
    <td>{$Syndication:item.failed_count|wash}</td>
    <td>{$Syndication:item.none_count|wash}</td>
    <td width="1">{section show=$Syndication:item.can_edit}<div class="listbutton"><a href={concat("syndication/import_edit/",$Syndication:item.id)|ezurl}><img class="button" src={"edit.png"|ezimage} width="16" height="16" alt="Edit" /></a></div>{/section}</td>
    <td width="1">{section show=$Syndication:item.can_remove}<input type="checkbox" name="RemoveImportIDArray[]" value="{$Syndication:item.id}">{/section}</td>
</tr>
{/section}
<tr>
  <td colspan="7">
    {include uri="design:gui/button.tpl" id_name=Create value="New Import"|i18n("design/standard/syndication/list")}
  </td>
  <td align="right">
    <input type="image" name="Remove" value="{'Remove'|i18n('design/standard/syndication/list')}" src={"trash.png"|ezimage} />
  </td>
</tr>
</table>
    </div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>

</form>

{/let}
