{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let uri=concat( 'syndication/list' )}

<form action={$uri|ezurl} method="post" name="Syndication">

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{"Syndication export list"|i18n("design/standard/syndication/list")}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

<div class="block">

<table class="list" width="100%" cellpadding="0" cellspacing="0" border="0">
<tr>
    <th>{"Name"|i18n("design/standard/syndication/list")}</th>
    <th>{"Active"|i18n("design/standard/syndication/list")}</th>
{*    <th>{"Last Export"|i18n("design/standard/syndication/list")}</th>
    <th>{"# subscribers"|i18n("design/standard/syndication/list")}</th>
    <th>{"# documents"|i18n("design/standard/syndication/list")}</th> *}
    <th>{"Edit"|i18n("design/standard/syndication/list")}</th>
    <th>{"Remove"|i18n("design/standard/syndication/list")}</th>
</tr>

{section name=Syndication loop=$feed_list sequence=array(bglight,bgdark)}
<tr>
    <td class="{$Syndication:sequence}">{$Syndication:item.name|wash}{* <a href={concat("syndication/feed_info/",$Syndication:item.id)|ezurl}>{$Syndication:item.name|wash}</a> *}</td>
    <td class="{$Syndication:sequence}">{section show=$Syndication:item.enabled}{"yes"|i18n("design/standard/syndication/list")}{section-else}{"no"|i18n("design/standard/syndication/list")}{/section}</td>
{*    <td class="{$Syndication:sequence}">TODO</td>
    <td class="{$Syndication:sequence}">TODO</td>
    <td class="{$Syndication:sequence}">{$Syndication:item.object_count}</td> *}
    <td class="{$Syndication:sequence}" width="1">{section show=$Syndication:item.can_edit}<div class="listbutton"><a href={concat("syndication/edit/",$Syndication:item.id)|ezurl}><img class="button" src={"edit.png"|ezimage} width="16" height="16" alt="Edit" /></a></div>{/section}</td>
    <td class="{$Syndication:sequence}" width="1">{section show=$Syndication:item.can_remove}<input type="checkbox" name="RemoveFeedIDArray[]" value="{$Syndication:item.id}">{/section}</td>
</tr>
{/section}
<tr>
  <td colspan="3">
    {include uri="design:gui/button.tpl" id_name=CreateButton value="New Feed"|i18n("design/standard/syndication/list")}
  </td>
  <td align="right">
    <input type="image" name="RemoveButton" value="{'Remove'|i18n('design/standard/syndication/list')}" src={"trash.png"|ezimage} />
  </td>
</tr>
</table>

    </div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>

</form>

{/let}