{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h2>{"Adding Feed Source"|i18n("design/standard/syndication/edit")}</h2>
<div class="block">
    <ol>
        {section show=$step|eq(1)}<b>{/section}<li>{"Add feed source type"|i18n("design/standard/syndication/edit")}</li>
            {section show=$step|eq(1)}</b>{/section}

        {section show=$step|eq(2)}<b>{/section}<li>{"Add source node"|i18n("design/standard/syndication/edit")}</li>
            {section show=$step|eq(2)}</b>{/section}

        {section show=$step|eq(3)}<b>{/section}<li>{"Add source filters"|i18n("design/standard/syndication/edit")}</li>
            {section show=$step|eq(3)}</b>{/section}
    </ol>
</div>