{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="maincontentheader">
<h1>
    {"Choose export node"|i18n("design/standard/syndication")}
</h1>
</div>

{let step=2}
{include uri="design:syndication/add_feed_source/add_feed_source_steps.tpl}
{/let}

<p>
    {"Please select the feed source.

    Select and click the %buttonname button.
    Using the recent and bookmark items for quick placement is also possible.
    Click on placement names to change the browse listing."
    |i18n("design/standard/syndication",,
          hash('%buttonname','Select'|i18n("design/standard/syndication")))
    |nl2br}
</p>